### PR TITLE
Make it work with Vue 3

### PR DESCRIPTION
**Pull request by FedorSherbakov**

### CODE REVIEW

**Comment by Wambosa** [comment]
This solution worked for me resolving issue https://github.com/sam3d/vue-svg/issues/10

**Comment by tompeace** [comment]
Any idea when this will be merged?

**Comment by sam3d** [comment]
Sorry for the delay on this, been so busy! Merged and released in v0.2.0 🎉

**Comment by vpillinger** [comment]
@sam3d Not having a PR is probably not too helpful but this PR doesn't actually make this work with webpack 5.

These three dependencies are still out of date and don't support webpack 5:

- file-loader
- svg-sprite-loader
- url-loader

It results in this error:

```
 INFO  Starting development server...
 ERROR  TypeError: Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at setup (/home/vincent/Projects/myProject/node_modules/vue-cli-plugin-svg-vue3/index.js:44:41)
    at /home/vincent/Projects/myProject/node_modules/vue-cli-plugin-svg-vue3/index.js:22:30
    at /home/vincent/Projects/myProject/node_modules/@vue/cli-service/lib/Service.js:252:40
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (/home/vincent/Projects/myProject/node_modules/@vue/cli-service/lib/Service.js:252:26)
    at Service.resolveWebpackConfig (/home/vincent/Projects/myProject/node_modules/@vue/cli-service/lib/Service.js:256:48)
    at PluginAPI.resolveWebpackConfig (/home/vincent/Projects/myProject/node_modules/@vue/cli-service/lib/PluginAPI.js:132:25)
    at serve (/home/vincent/Projects/myProject/node_modules/@vue/cli-service/lib/commands/serve.js:73:31)
    at Service.run (/home/vincent/Projects/myProject/node_modules/@vue/cli-service/lib/Service.js:246:12)
    ```

**Pull request merged**
